// GENERATED by packages/domain-spec/generate.py - DO NOT EDIT.
// Derived from the dartboard segment set by enumeration. specVersion 1.1.0.
package thro.engine

public object RuleTables {
    public const val SPEC_VERSION: String = "1.1.0"
    public const val MAX_VISIT_TOTAL: Int = 180

    /** Totals no three darts can produce. Validating 0..180 alone is wrong. */
    public val IMPOSSIBLE_VISIT_TOTALS: Set<Int> = setOf(163, 166, 169, 172, 173, 175, 176, 178, 179)

    /** No visit can exceed the maximum, so bust cannot occur at or above this. */
    public const val BUST_IMPOSSIBLE_AT_OR_ABOVE: Int = 182

    private val BOGEYS_DOUBLE: IntArray = intArrayOf(159, 162, 163, 165, 166, 168, 169)
    private const val MAX_DOUBLE: Int = 170
    private val BOGEYS_MASTER: IntArray = intArrayOf(163, 166, 169, 172, 173, 175, 176, 178, 179)
    private const val MAX_MASTER: Int = 180
    private val BOGEYS_STRAIGHT: IntArray = intArrayOf(163, 166, 169, 172, 173, 175, 176, 178, 179)
    private const val MAX_STRAIGHT: Int = 180

    public val ONE_DART_FINISHES_DOUBLE: Set<Int> = setOf(2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 50)

    private val CHECKOUTS_DOUBLE: Set<Int> = build(MAX_DOUBLE, BOGEYS_DOUBLE)
    private val CHECKOUTS_MASTER: Set<Int> = build(MAX_MASTER, BOGEYS_MASTER)
    private val CHECKOUTS_STRAIGHT: Set<Int> = build(MAX_STRAIGHT, BOGEYS_STRAIGHT)

    public fun checkouts(outRule: OutRule): Set<Int> = when (outRule) {
        OutRule.DOUBLE -> CHECKOUTS_DOUBLE
        OutRule.MASTER -> CHECKOUTS_MASTER
        OutRule.STRAIGHT -> CHECKOUTS_STRAIGHT
    }

    private fun build(max: Int, bogeys: IntArray): Set<Int> {
        val bad = bogeys.toHashSet()
        val out = HashSet<Int>(max)
        for (v in 2..max) if (v !in bad) out.add(v)
        return out
    }
}
