// GENERATED by packages/domain-spec/generate.py - DO NOT EDIT.
// Derived from the dartboard segment set by enumeration. specVersion 1.3.0.
package thro.engine

public object RuleTables {
    public const val SPEC_VERSION: String = "1.3.0"
    public const val MAX_VISIT_TOTAL: Int = 180

    /** Totals no three darts can produce. Validating 0..180 alone is wrong. */
    public val IMPOSSIBLE_VISIT_TOTALS: Set<Int> = setOf(163, 166, 169, 172, 173, 175, 176, 178, 179)

    /** No visit can exceed the maximum, so bust cannot occur at or above this. */
    public const val BUST_IMPOSSIBLE_AT_OR_ABOVE: Int = 182

    private val BOGEYS_DOUBLE: IntArray = intArrayOf(159, 162, 163, 165, 166, 168, 169)
    private const val MIN_DOUBLE: Int = 2
    private const val MAX_DOUBLE: Int = 170
    private val BOGEYS_MASTER: IntArray = intArrayOf(163, 166, 169, 172, 173, 175, 176, 178, 179)
    private const val MIN_MASTER: Int = 2
    private const val MAX_MASTER: Int = 180
    private val BOGEYS_STRAIGHT: IntArray = intArrayOf(163, 166, 169, 172, 173, 175, 176, 178, 179)
    private const val MIN_STRAIGHT: Int = 1
    private const val MAX_STRAIGHT: Int = 180

    public val ONE_DART_FINISHES_DOUBLE: Set<Int> = setOf(2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 50)

    private val CHECKOUTS_DOUBLE: Set<Int> = build(MIN_DOUBLE, MAX_DOUBLE, BOGEYS_DOUBLE)
    private val CHECKOUTS_MASTER: Set<Int> = build(MIN_MASTER, MAX_MASTER, BOGEYS_MASTER)
    private val CHECKOUTS_STRAIGHT: Set<Int> = build(MIN_STRAIGHT, MAX_STRAIGHT, BOGEYS_STRAIGHT)

    public fun checkouts(outRule: OutRule): Set<Int> = when (outRule) {
        OutRule.DOUBLE -> CHECKOUTS_DOUBLE
        OutRule.MASTER -> CHECKOUTS_MASTER
        OutRule.STRAIGHT -> CHECKOUTS_STRAIGHT
    }

    /**
     * Counted totals a visit can record while the player has not yet opened (PD-008).
     *
     * A legal opening segment plus up to two free darts after it. Under double-in the
     * bull opens, so the largest is D25+T20+T20 = 170; the totals three darts can make
     * but no opening sequence can are 1, 159, 162, 165, 168, 171, 174, 177, 180.
     */
    private val UNOPENABLE_DOUBLE: IntArray = intArrayOf(1, 159, 162, 165, 168, 171, 174, 177, 180)
    private const val MAX_OPENING_DOUBLE: Int = 170
    private val UNOPENABLE_MASTER: IntArray = intArrayOf(1)
    private const val MAX_OPENING_MASTER: Int = 180
    private val UNOPENABLE_STRAIGHT: IntArray = intArrayOf()
    private const val MAX_OPENING_STRAIGHT: Int = 180

    private val OPENING_DOUBLE: Set<Int> = opening(MAX_OPENING_DOUBLE, UNOPENABLE_DOUBLE)
    private val OPENING_MASTER: Set<Int> = opening(MAX_OPENING_MASTER, UNOPENABLE_MASTER)
    private val OPENING_STRAIGHT: Set<Int> = opening(MAX_OPENING_STRAIGHT, UNOPENABLE_STRAIGHT)

    public fun openingTotals(inRule: InRule): Set<Int> = when (inRule) {
        InRule.DOUBLE -> OPENING_DOUBLE
        InRule.MASTER -> OPENING_MASTER
        InRule.STRAIGHT -> OPENING_STRAIGHT
    }

    private fun opening(max: Int, unopenable: IntArray): Set<Int> {
        val bad = unopenable.toHashSet()
        val out = HashSet<Int>(max)
        for (v in 1..max) if (v !in bad && v !in IMPOSSIBLE_VISIT_TOTALS) out.add(v)
        return out
    }

    /** The floor is the rule's own: under straight-out a single 1 finishes. */
    private fun build(min: Int, max: Int, bogeys: IntArray): Set<Int> {
        val bad = bogeys.toHashSet()
        val out = HashSet<Int>(max)
        for (v in min..max) if (v !in bad) out.add(v)
        return out
    }
}
