#!/usr/bin/env python3
"""The Android launcher icon, drawn from the mark's own geometry.

**The problem it solves.** `apps/android/app/src/main/res` had no icon in it at all, so Android fell back
to the default green robot — the first thing anybody sees of THRØ on that platform was somebody else's
logo on the brand's green.

**Generated, not drawn.** The obvious fix is to export a PNG from the iOS icon and drop it in. That would
work today and drift tomorrow: the mark is defined by four ratios in `MarkGeometry.Ratios.mark`, the
animated opening interpolates them, and an exported bitmap knows none of that. So this reads the ratios
out of `Geometry.swift` and the two colours out of the generated design tokens, and writes the vector.
Change a ratio and re-run, and the launcher icon moves with the mark. `--check` fails if it has not.

Those ratios were verified against the shipped iOS icon rather than trusted: scanning the centre row of
`AppIcon.png` gives an outer ring radius of 0.2607 of the canvas and an inner of 0.1797, whose quotient is
0.689 against the ratios' 0.687, and a bar half-width of 0.040 of the unit once the 45° cut is divided out.

**The scale is the interesting decision.** iOS gets a 1024 square and the mark's tips reach 92% of the way
to the edge. Android hands you a 108×108dp canvas of which only the central **72×72dp is guaranteed
visible** — the rest is margin the launcher may crop, animate or parallax away. Filling 108 would put the
tips outside every circular mask on the market. So 72 is treated as the icon, exactly as 1024 is on iOS,
which lands the tips at 92% of *that* radius: the same drawing, at the same proportion, in the space each
platform actually shows.

**And a monochrome layer**, because Android 13 themed icons will otherwise invent one by desaturating the
foreground, and the mark tinted by the wallpaper is better than the mark guessed at.

Run:  python3 tools/make_android_icon.py
      python3 tools/make_android_icon.py --check
"""

from __future__ import annotations

import math
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
GEOMETRY = ROOT / "packages/client-ios/Sources/ThroDesign/Geometry.swift"
TOKENS = ROOT / "packages/design-tokens/generated/tokens.css"
RES = ROOT / "apps/android/app/src/main/res"

# Android's adaptive-icon canvas, and the part of it a launcher promises to show.
CANVAS = 108.0
VISIBLE = 72.0
# The mark's unit as a fraction of the visible square, measured off the shipped iOS icon:
# ringOuter is 0.2607 of that icon's canvas and ringOuter = 0.364 × unit.
UNIT_OF_VISIBLE = 0.2607 / 0.364

BANNER = "<!-- Generated by tools/make_android_icon.py from MarkGeometry.Ratios.mark. Do not edit. -->"


def ratios() -> dict[str, float]:
    """`Ratios.mark` as written in Swift. One source, and it is the one the app draws from."""
    text = GEOMETRY.read_text()
    match = re.search(
        r"static let mark = Ratios\(ringOuter:\s*([\d.]+),\s*ringInner:\s*([\d.]+),"
        r"\s*halfWidth:\s*([\d.]+),\s*tip:\s*([\d.]+)\)",
        text,
    )
    if not match:
        raise SystemExit(f"could not find Ratios.mark in {GEOMETRY.relative_to(ROOT)}")
    outer, inner, half, tip = (float(g) for g in match.groups())
    return {"ringOuter": outer, "ringInner": inner, "halfWidth": half, "tip": tip}


def token(name: str) -> str:
    """A colour from the generated tokens, light mode — the first definition in the file."""
    match = re.search(rf"^\s*--{re.escape(name)}:\s*(#[0-9A-Fa-f]{{6}});", TOKENS.read_text(), re.M)
    if not match:
        raise SystemExit(f"no --{name} in {TOKENS.relative_to(ROOT)}")
    return match.group(1).upper()


def circle(cx: float, cy: float, r: float) -> str:
    """A closed circle in SVG path commands, which is what a vector drawable's pathData speaks."""
    return (f"M{cx - r:.3f},{cy:.3f}"
            f"a{r:.3f},{r:.3f} 0 1,0 {2 * r:.3f},0"
            f"a{r:.3f},{r:.3f} 0 1,0 {-2 * r:.3f},0z")


def foreground(r: dict[str, float], colour: str) -> str:
    unit = UNIT_OF_VISIBLE * VISIBLE
    c = CANVAS / 2
    outer, inner = r["ringOuter"] * unit, r["ringInner"] * unit
    half, tip = r["halfWidth"] * unit, r["tip"] * unit
    k = math.sqrt(0.5)

    def on_axis(d: float, v: float = 0.0) -> tuple[float, float]:
        """`MarkGeometry.onAxis`, transcribed: `d` along the 45° axis, `v` across it."""
        return (c + d * k - v * k, c - d * k - v * k)

    # Tip, shoulder, shoulder, tip, shoulder, shoulder — the bar's six corners, as in `barPoints`.
    bar = [on_axis(tip), on_axis(outer, half), on_axis(-outer, half),
           on_axis(-tip), on_axis(-outer, -half), on_axis(outer, -half)]
    bar_data = "M" + "L".join(f"{x:.3f},{y:.3f}" for x, y in bar) + "z"

    # The ring and the bar are two paths of the same colour rather than one. Swift has to merge them
    # into a single wound path because it fills once; here they are separate elements, so the crossing
    # cannot cancel itself out — which is the bug the Swift comment records having shipped.
    return f"""{BANNER}
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <!-- The ring: outer circle less inner, by the even-odd rule. -->
    <path
        android:fillColor="{colour}"
        android:fillType="evenOdd"
        android:pathData="{circle(c, c, outer)}{circle(c, c, inner)}" />
    <!-- The dart: parallel-sided where it crosses the ring, tapering to a point at each end. -->
    <path
        android:fillColor="{colour}"
        android:pathData="{bar_data}" />
</vector>
"""


def launcher(round_: bool) -> str:
    return f"""{BANNER}
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/thro_icon_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
    <!-- Android 13 themed icons. Without this the launcher desaturates the foreground and guesses;
         the mark tinted by the wallpaper is better than the mark guessed at. -->
    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />
</adaptive-icon>
"""


def colours(field: str) -> str:
    # No custom-property name in the comment: XML forbids the two-character sequence a CSS variable
    # starts with anywhere inside a comment, and AAPT's parser is strict about it.
    return f"""{BANNER}
<resources>
    <!-- The color-board-field token, which is also the exported iOS icon's own corner pixel. -->
    <color name="thro_icon_background">{field}</color>
</resources>
"""


FILES = {
    "drawable/ic_launcher_foreground.xml": lambda r, chalk, field: foreground(r, chalk),
    # The monochrome layer is the same drawing in a colour the system replaces. Black is the
    # convention: the launcher reads the alpha and tints it.
    "drawable/ic_launcher_monochrome.xml": lambda r, chalk, field: foreground(r, "#FF000000"),
    "mipmap-anydpi-v26/ic_launcher.xml": lambda r, chalk, field: launcher(False),
    "mipmap-anydpi-v26/ic_launcher_round.xml": lambda r, chalk, field: launcher(True),
    "values/thro_icon.xml": lambda r, chalk, field: colours(field),
}


def main() -> int:
    checking = "--check" in sys.argv
    r = ratios()
    chalk, field = token("thro-chalk"), token("color-board-field")

    stale = []
    for name, build in FILES.items():
        path = RES / name
        wanted = build(r, chalk, field)
        if checking:
            if not path.exists() or path.read_text() != wanted:
                stale.append(name)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(wanted)

    if checking:
        if stale:
            print("The launcher icon no longer matches the mark's geometry:\n")
            for name in stale:
                print(f"  {name}")
            print("\n  Re-run: python3 tools/make_android_icon.py")
            return 1
        print(f"the launcher icon is the mark — ringOuter {r['ringOuter']}, tip {r['tip']}, on {field}")
        return 0

    print(f"wrote {len(FILES)} files under {RES.relative_to(ROOT)} from Ratios.mark and the tokens")
    return 0


if __name__ == "__main__":
    sys.exit(main())
