// GENERATED by packages/domain-spec/generate.py - DO NOT EDIT.
// Derived from the dartboard segment set by enumeration. specVersion 1.3.0.

public enum RuleTables {
    public static let specVersion = "1.3.0"
    public static let maxVisitTotal = 180

    /// Totals no three darts can produce. Validating 0...180 alone is wrong.
    public static let impossibleVisitTotals: Set<Int> = [163, 166, 169, 172, 173, 175, 176, 178, 179]

    /// No visit can exceed the maximum, so bust cannot occur at or above this.
    public static let bustImpossibleAtOrAbove = 182

    private static let bogeysDouble: Set<Int> = [159, 162, 163, 165, 166, 168, 169]
    private static let minDouble = 2
    private static let maxDouble = 170
    private static let bogeysMaster: Set<Int> = [163, 166, 169, 172, 173, 175, 176, 178, 179]
    private static let minMaster = 2
    private static let maxMaster = 180
    private static let bogeysStraight: Set<Int> = [163, 166, 169, 172, 173, 175, 176, 178, 179]
    private static let minStraight = 1
    private static let maxStraight = 180

    public static let oneDartFinishesDouble: Set<Int> = [2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 50]

    private static let checkoutsDouble = build(minDouble, maxDouble, bogeysDouble)
    private static let checkoutsMaster = build(minMaster, maxMaster, bogeysMaster)
    private static let checkoutsStraight = build(minStraight, maxStraight, bogeysStraight)

    public static func checkouts(_ outRule: OutRule) -> Set<Int> {
        switch outRule {
        case .double: return checkoutsDouble
        case .master: return checkoutsMaster
        case .straight: return checkoutsStraight
        }
    }

    /// Counted totals a visit can record while the player has not yet opened (PD-008):
    /// a legal opening segment plus up to two free darts after it. Under double-in the
    /// bull opens, so the largest is D25+T20+T20 = 170.
    private static let unopenableDouble: Set<Int> = [1, 159, 162, 165, 168, 171, 174, 177, 180]
    private static let maxOpeningDouble = 170
    private static let unopenableMaster: Set<Int> = [1]
    private static let maxOpeningMaster = 180
    private static let unopenableStraight: Set<Int> = []
    private static let maxOpeningStraight = 180

    private static let openingDouble = opening(maxOpeningDouble, unopenableDouble)
    private static let openingMaster = opening(maxOpeningMaster, unopenableMaster)
    private static let openingStraight = opening(maxOpeningStraight, unopenableStraight)

    public static func openingTotals(_ inRule: InRule) -> Set<Int> {
        switch inRule {
        case .double: return openingDouble
        case .master: return openingMaster
        case .straight: return openingStraight
        }
    }

    private static func opening(_ max: Int, _ unopenable: Set<Int>) -> Set<Int> {
        var out = Set<Int>(minimumCapacity: max)
        for v in 1...max where !unopenable.contains(v) && !impossibleVisitTotals.contains(v) {
            out.insert(v)
        }
        return out
    }

    /// The floor is the rule's own: under straight-out a single 1 finishes.
    private static func build(_ min: Int, _ max: Int, _ bogeys: Set<Int>) -> Set<Int> {
        var out = Set<Int>(minimumCapacity: max)
        for v in min...max where !bogeys.contains(v) { out.insert(v) }
        return out
    }
}
