// GENERATED by packages/domain-spec/generate.py - DO NOT EDIT.
// Derived from the dartboard segment set by enumeration. specVersion 1.2.0.

public enum RuleTables {
    public static let specVersion = "1.2.0"
    public static let maxVisitTotal = 180

    /// Totals no three darts can produce. Validating 0...180 alone is wrong.
    public static let impossibleVisitTotals: Set<Int> = [163, 166, 169, 172, 173, 175, 176, 178, 179]

    /// No visit can exceed the maximum, so bust cannot occur at or above this.
    public static let bustImpossibleAtOrAbove = 182

    private static let bogeysDouble: Set<Int> = [159, 162, 163, 165, 166, 168, 169]
    private static let maxDouble = 170
    private static let bogeysMaster: Set<Int> = [163, 166, 169, 172, 173, 175, 176, 178, 179]
    private static let maxMaster = 180
    private static let bogeysStraight: Set<Int> = [163, 166, 169, 172, 173, 175, 176, 178, 179]
    private static let maxStraight = 180

    public static let oneDartFinishesDouble: Set<Int> = [2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 50]

    private static let checkoutsDouble = build(maxDouble, bogeysDouble)
    private static let checkoutsMaster = build(maxMaster, bogeysMaster)
    private static let checkoutsStraight = build(maxStraight, bogeysStraight)

    public static func checkouts(_ outRule: OutRule) -> Set<Int> {
        switch outRule {
        case .double: return checkoutsDouble
        case .master: return checkoutsMaster
        case .straight: return checkoutsStraight
        }
    }

    private static func build(_ max: Int, _ bogeys: Set<Int>) -> Set<Int> {
        var out = Set<Int>(minimumCapacity: max)
        for v in 2...max where !bogeys.contains(v) { out.insert(v) }
        return out
    }
}
